#source :rubygems
source 'https://rubygems.org'
#source 'http://ruby.taobao.org'
gem 'sinatra'
gem 'slim'
gem 'sass'
gem 'dm-core'
gem 'dm-migrations'
gem 'sinatra-flash'
gem 'coffee-script'
gem 'thin'
#gem 'therubyracer' # The Ruby Racer gem is unnecessary if you have Node.js installed on your system.
gem 'therubyracer', :group => :production
gem 'sinatra-reloader', :group => :development
gem 'pony', :group => :development
gem 'pg', :group => :production
gem 'dm-postgres-adapter', :group => :production
gem 'dm-sqlite-adapter', :group => :development