#source :rubygems
source 'https://rubygems.org'
#source 'http://ruby.taobao.org'
gem 'sinatra'
gem 'slim'
gem 'sass'
gem 'dm-core'
gem 'dm-migrations'
gem 'sinatra-flash'
gem 'coffee-script'
gem 'thin'
gem 'pony'

group :development do
  gem 'sinatra-reloader'
  gem 'dm-sqlite-adapter'
end

group :production do
  gem 'json'
  gem 'mysql2'
  gem 'therubyracer' # The Ruby Racer gem is unnecessary if you have Node.js installed on your system.
  gem 'dm-mysql-adapter'
end
